version: "3"

services:
        mysql:
                image: mysql:5.7
                container_name: mysql_1
                ports:
                        - 3306:3306
                environment:
                        MYSQL_DATABASE: demo_db
                        MYSQL_USER: demo_db
                        MYSQL_PASSWORD: root
                        MYSQL_ROOT_PASSWORD: root
                volumes: 
                        - ./data/databases_root/demo_db:/var/lib/mysql
                        - /etc/localtime:/etc/localtime:ro
                restart: always 
                command: [
                        '--character-set-server=utf8',
                        '--collation-server=utf8_general_ci',
                        '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
                        ]