apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  #volumeMode: Filesystem  #https://stackoverflow.com/questions/52217988/unknown-field-storage-in-io-k8s-api-core-v1-persistentvolumeclaim/52218044
  resources:
    requests:
      storage: 1Gi #持久卷的容量是 1 GB