apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  mysql-user-root-pwd: cm9vdA== # database password for "root"
  mysql-user-dbuser-name: ZGJ1c2Vy # database user name for "dbuser"
  mysql-user-dbuser-pwd: ZGJ1c2Vy # database password for "dbuser"